### ISSUE TITLE
[Bug] Incompatability with Krowi's Achievement Filter?

### ISSUE THREAD

**Issue by Beet4** [wind-addons/ElvUI_WindTools#294]
**Describe the bug**
There seems to be some kind of weird incompatibility issue with Krowi's Achievement Filter. If you have progression enabled in WindTools tooltip module enabled and Krowi's Achievement Filter installed sometimes when pressing the modifier key for WindTools tooltip module the compare achievement window popups if hovering another player. It's really annoying mid-combat.

If you join Krowi's discord and then follow this the link in this post you can read more: 
https://www.curseforge.com/wow/addons/krowi-achievement-filter?comment=134

There is also a post there with some LUA error WindTools sometimes generate even without this addon installed that might be related.

Just wanted to make you aware of this, don't know if it's WindTools fault or Krowi's fault.

**To Reproduce**
1. Krowi's Achievement Filter
2. Enable progression and tooltip module of WindTools
3. Use the modifier key during combat and hover over another player
4. Sometimes the achievement window popups.

**Comment by fang2hou** [comment]
I don't think that issue is from WindTools, because I never heard the bug like this.
Did you test with `/wtdebug on`?
