### ISSUE TITLE
[Bug] Iskaaran Fishing Nets wrong timer

### ISSUE THREAD

**Issue by deadlydag** [wind-addons/ElvUI_WindTools#297]
Looks like the upgrades to the fishing nets is not included, so the timers are very wrong.
I have 6 hour timers since I have gotten the upgrades, but it still shows as 10 hours on the module.

**Comment by fang2hou** [comment]
the 10 hours timer is hard code in addon, and what's the upgrade of fishing net? I am very curious of this fishing game play.
I want the details like the quest done, level up the reknown to xx, achievement got, etc.

**Comment by deadlydag** [comment]
Once you hit level 13 with the Iskaara Tuskarr faction, you can upgrade your fishing-items.
You can learn to make two improvements to your net - [Draconium Net Weights](https://www.wowhead.com/item=199848/draconium-net-weights) and [Imbu Knot](https://www.wowhead.com/item=199850/imbu-knot) -- which increase the capacity and fill speed of your fishing net.

While the [Draconium Net Weights] doesn't affect your filling-speed, if you get the [Imbu Knot], your timer goes from 10 hours down to 6 hours to fill one fishing net.

You can also have 3 fishing nets up at all times.
I'm not sure how it works, because the daily-quests seems random - but there are two daily-quests at one fishing-hub, and thats the place you get 2x fishing nets.
On the other fishing-hub, you only get 1x fishing net.
But in total there are 3x up at all times.

You can also upgrade your [Imbu Knot] to [Double Imbu Knot] https://www.wowhead.com/item=199851/double-imbu-knot at a higher level, but I haven't gotten that far yet, so I'm not sure how many hours it is.

**Comment by fang2hou** [comment]
> Once you hit level 13 with the Iskaara Tuskarr faction, you can upgrade your fishing-items. You can learn to make two improvements to your net - [Draconium Net Weights](https://www.wowhead.com/item=199848/draconium-net-weights) and [Imbu Knot](https://www.wowhead.com/item=199850/imbu-knot) -- which increase the capacity and fill speed of your fishing net.
> 
> While the [Draconium Net Weights] doesn't affect your filling-speed, if you get the [Imbu Knot], your timer goes from 10 hours down to 6 hours to fill one fishing net.
> 
> You can also have 3 fishing nets up at all times. I'm not sure how it works, because the daily-quests seems random - but there are two daily-quests at one fishing-hub, and thats the place you get 2x fishing nets. On the other fishing-hub, you only get 1x fishing net. But in total there are 3x up at all times.
> 
> You can also upgrade your [Imbu Knot] to [Double Imbu Knot] https://www.wowhead.com/item=199851/double-imbu-knot at a higher level, but I haven't gotten that far yet, so I'm not sure how many hours it is.

Very clear!
I will take a look in the future version.

**Comment by fang2hou** [comment]
After upgrading the fishing net, is the [Imbu Knot](https://www.wowhead.com/item=199850/imbu-knot) in your bag or just disappeared in fishing gear craft UI?

**Comment by fang2hou** [comment]
New logic has been added in 3.20 version, if you found the fishing net not recorded, please use command `/wtet findNet` in-game, and post the output here.

**Comment by fang2hou** [comment]
Because it is time to 11.0, this issue won't be fix.
