### ISSUE TITLE
在鼠标提示面板添加装等+天赋提示，类似Shadow&Light里的角色面板附魔宝石检测，LFG大秘境分数排序

### ISSUE THREAD

**Issue by SneaXyx** [wind-addons/ElvUI_WindTools#306]
**描述问题**
功能添加建议

**预期功能**
我个人对插件方面小有研究，也喜欢自己去改一些做好的WA来完善自己的体验，我很喜欢wind工具箱这个插件，也是自从开始使用elvui之后不能离开工具箱。

1. 现有的TinyInpect插件的角色观察和属性对比功能，工具箱已经能完美替代了，但是唯一的一个功能，就是TinyInspect里面的在鼠标提示面板里面显示当前角色的装等以及天赋，工具箱暂时没有。
Elvui的自带设置要求使用者按住修饰键（Shift）才能得以看到装等以及天赋，但是，在按住修饰按键的时候，还有很多不必要的信息，列如通关大秘境的层数和团本进度，这些会无故增加用户需要去自己查找装等的时间。

我的想法是，能否修改部分的内容，然后能够在不用按住修饰按键的同时，能够在鼠标提示的面板里显示玩家甚至观察的别的角色的装等以及天赋，然后按住修饰键所显示的内容不需要更改，还是会显示更详细的信息

2. shadow&light是另外一个elvui的增强插件，除了一些工具箱已有的功能（列如加强阴影，团队标记etc.）之外，有一项比较核心的功能就是armory mode。
简单来说，armory mode就是一个可以在角色观察界面（个人和他人），可以看到自己的装备的附魔和宝石，也会在装备没有附魔的时候加上颜色来提示玩家去附魔或者打宝石。

3. 3.21版本的工具箱更新的LFG的面板我特别特别喜欢，我原本是一个premadegroupfilter 插件的用户，但是因为工具箱更新的这个功能，我已经可以省去用这个插件的必要了。我有一个希望可以改进的点，就是在LFG的界面能够把队长的分数以升序或者降序来排列，（wago上有一个wa是一个很好的例子，详见截图）

**截图**
[https://imgur.com/gallery/byhEgMH](url)

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: 3.21
 - ElvUI 版本: 13.21
 - 游戏版本 : 10.0.2 (本帖写于10.0.5更新前夕)
**更多信息**
如果你有更多信息, 在这里填写.

**Comment by fang2hou** [comment]
1. 这个其实已经讨论过非常多次了, 查询装等的背后其实是对该玩家进行完整的服务器请求查询, 会对游戏造成额外的负担. 最常见的负担场景就是主城鼠标移动时可能会被卡掉线. 为了更加稳定的游戏体验, 国外大部分参与过讨论的插件作者都将装等功能放置到了修饰键中. 故虽然是可以做, 但是 Wind 工具箱不会加入此支持. 为了解决这个问题, 其实只需要换个修饰键就行, 在 Wind 工具箱鼠标提示设定的最上方可以找到.

2. 每个插件都应该有其特色, 每个作者也有其喜好. 这个确实是很多人都在提, 但是插件的代码移植不是说移植就能移植的. TinyInspect 的功能移植是和 TinyInspect 作者交流后获得授权的. 我个人也觉得 TinyInspect 更加清晰明了, 遗失的附魔也会有提示. 你依旧可以继续使用 S&L, 兼容性助手也是为了这种情况制作的.

3. 排序功能已经在制作了, 只是在思考 UI 设计. 之后这个模块也将剥离出来作为单体插件提供, 以替代集合石.
