### ISSUE TITLE
Openable items added to toolbar

### ISSUE THREAD

**Issue by pcangelnc** [wind-addons/ElvUI_WindTools#352]
I notice that "Crate of Dreambound Armor", ID 209833, has been added to the openable items and so appears on an Extra Item Bar.  The problem is that the item itself is BOA.  This makes it easy to click to open when the intention instead may be to send to an alt. 

I would suggest not adding these types of BOA openable things to the openable category and let users add it in Custom if they so chose.

**Comment by fang2hou** [comment]
It has been fixed before.
