### ISSUE TITLE
[Bug] Switch buttons in quest doesn't hide with objective tracker

### ISSUE THREAD

**Issue by claytonkimber** [wind-addons/ElvUI_WindTools#371]
**Describe the bug**
When clicking the hide/show objective tracker button, the "Switch buttons" panel is shown with the "hide with Objective tracker" checked where it shouldn't be

**To Reproduce**
Go to Quest - Switch buttons
Enable switch buttons
Hide objectives

**Expected behavior**
Switch buttons for turn in and announcement should hide as expected

**Screenshots**
![Screenshot 2024-01-17 214948](https://github.com/fang2hou/ElvUI_WindTools/assets/6076740/aa2b9198-c739-48c4-97e7-0be82dd0f6b9)
![Screenshot 2024-01-17 215051](https://github.com/fang2hou/ElvUI_WindTools/assets/6076740/86137ad0-9517-483d-bd62-d46c834c34a0)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.48
 - ElvUI Version 13.55
 - WoW Build 10.2.5

**Additional context**

**Comment by fang2hou** [comment]
It should be fixed in the latest versions.
