### ISSUE TITLE
[Bug] Absorb module's method ProfileUpdate cause 'script ran too long' lua error

### ISSUE THREAD

**Issue by Issacy** [wind-addons/ElvUI_WindTools#373]
**描述问题**
在与ElvUI EltreumUI插件一起使用时, 进入永恒黎明地下城, 大概率在执行Core:UpdateModules函数时报错, 错误提示为'script ran too long'
经排查发现, 是在执行Absorb模块的ProfileUpdate函数时, 其不论模块是否启用, 都会调用UF:Update_AllFrames, 导致函数执行耗时过长
(因不使用Absorb模块)删除UF:Update_AllFrames的调用后, 不再报错
且经初步代码分析, 怀疑(未认证)此模块的ProfileUpdate函数实现可能存在逻辑错误

**错误复现**
错误复现步骤:
1. 到达永恒黎明副本外
2. 进入永恒黎明副本
3. 进入后立即触发报错

**插件信息 (请填写基本信息, 你可以在 [信息] 中找到):**
 - 插件版本: 3.48
 - ElvUI 版本: 13.55
 - 游戏版本: 10.2.5

**更多信息**
10.2.0时亦有此报错
未测试在不使用ElvUI EltreumUI插件时的表现
因不使用Absorb模块, 亦未能排查在启用状态下的逻辑合理性

**Comment by fang2hou** [comment]
ProfileUpdate 应该是仅会在配置文件更新时被调用, 钩子设定在这个函数上也是为了减少调用次数.
有其他插件自动在切换配置啥的吗?
