### ISSUE TITLE
[Bug] The 'Fix duplicated party in lfg frame' option makes the applications sort to the bottom 

### ISSUE THREAD

**Issue by DimitrisLK** [wind-addons/ElvUI_WindTools#379]
**Describe the bug**
With the `Fix duplicated party in lfg frame` option enabled, the LFG window bugs out and always sorts the groups you have applied to to the bottom of it. 

**To Reproduce**
1. Go to the `Advanced` options of Windtools and then `Game Fix`
2. Click on `Fix duplicated party in lfg frame`
3. Apply to a group in LFG
4. Refresh and the applications are sorted to the bottom of it.

**Expected behavior**
The applications should stay at the top of the frame. 

**Screenshots**
![image](https://github.com/fang2hou/ElvUI_WindTools/assets/32920285/6d8ee9c0-9521-41bf-a05b-c02b61932c7c)
![image](https://github.com/fang2hou/ElvUI_WindTools/assets/32920285/a5809704-3259-44f7-961a-8b7ba3196e40)

**Information (you can find these in [WindTools-Information]):**
 - Addon Version: 3.49
 - ElvUI Version: 13.57
 - WoW Build [10.2.5 (53262)]

**Comment by fang2hou** [comment]
because the fix is outdated, it has been removed in 3.68.
