### ISSUE TITLE
[Bug] some chat related LUA error started popping up today

### ISSUE THREAD

**Issue by jacho981** [wind-addons/ElvUI_WindTools#383]
today i started getting this error randomly. wasnt doing anything special, just chilling in valdrakken.
game and addons in its latest version.

10x ...eElvUI_WindTools/Modules/Social/ChatText.lua:2007: attempt to concatenate a nil value
[string "@ElvUI_WindTools/Modules/Social/ChatText.lua"]:2007: in function `BN_FRIEND_INFO_CHANGED'
[string "@ElvUI_WindTools/Modules/Social/ChatText.lua"]:1976: in function <...eElvUI_WindTools/Modules/Social/ChatText.lua:1974>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@ElvUI_WindTools/Modules/Social/ChatText.lua"]:1971: in function `?'
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:363
 Enable = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:290
 UnregisterAllEvents = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 EnableModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:438
 defaultModuleLibraries = <table> {
 }
 ElvUIChat_GuildMemberStatusMessageHandler = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1798
 bnetFriendDataCached = true
 SendAchivementMessage = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1652
 SetDefaultModulePrototype = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 ChatFrame_MessageEventHandler = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:592
 ElvUIChat_AchievementMessageHandler = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1710
 ToggleReplacement = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1578
 name = "ElvUI_WindTools_ChatText"
 Initialize = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:2055
 IsEnabled = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 AddMessage = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:508
 DisableModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:346
 baseName = "ElvUI_WindTools"
 Log = <function> defined @ElvUI_WindTools/Core/Functions/Developer.lua:124
 CheckLFGRoles = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:539
 cache = <table> {
 }
 RegisterMessage = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 ProfileUpdate = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:2070
 BN_FRIEND_INFO_CHANGED = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1969
 PLAYER_ENTERING_WORLD = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1959
 BetterSystemMessage = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1850
 isSystemMessageHandled = true
 IsModule = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:213
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:383
 MessageFormatter = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:1347
 HandleName = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:565
 SetEnabledState = <function> defined @ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 MayHaveBrackets = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:584
 enabledState = true
 HandleShortChannels = <function> defined @ElvUI_WindTools/Modules/Social/ChatText.lua:477
 RegisterEvent = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterAllMessages = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 ShortChannel = <function> defined @ElvUI_WindTools/

**Comment by fang2hou** [comment]
It cannot reproduce in my client, and if you meet this again, reopen this issue
