### ISSUE TITLE
[Feature Request] Make the Event Trackers on the World Map wrap to two lines if more than 3 shown

### ISSUE THREAD

**Issue by Fraktyl** [wind-addons/ElvUI_WindTools#384]
**Describe the bug**
Currently if you enable all the Event Trackers it just continues out past the Map fram

**To Reproduce**
Enable all trackers
Open map

**Expected behavior**
Working as intended now.  WOuld be nice if it wrapped.

**Screenshots**
![image](https://github.com/fang2hou/ElvUI_WindTools/assets/478132/e86c23ea-607b-42ff-a32b-80227b7829c4)

**Comment by Akwd22** [comment]
I confirm, even after the new update `3.55-fix-1`.

**Comment by fang2hou** [comment]
@Akwd22 
did you try reset the module?
the option of width of the timer will be added in the next version, currently the default option should work

**Comment by fang2hou** [comment]
I've added new logic for position calculation in 3.56, you can try it

**Comment by Akwd22** [comment]
It's now working perfectly. Thanks for your work.
