### ISSUE TITLE
[Bug]Lua Error LFG 

### ISSUE THREAD

**Issue by Jaidy88** [wind-addons/ElvUI_WindTools#388]
2x [ADDON_ACTION_BLOCKED] AddOn 'ElvUI_WindTools' hat versucht die geschützte Funktion 'ApplyToGroup()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `ApplyToGroup'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:3037: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:3034>
[string "=[C]"]: in function `Click'
[string "@ElvUI_WindTools/Modules/Misc/LFGList.lua"]:634: in function <...faceElvUI_WindTools/Modules/Misc/LFGList.lua:628>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Blizzard_StaticPopup/Mainline/StaticPopup.lua"]:1145: in function `StaticPopupSpecial_Show'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2966: in function `LFGListApplicationDialog_Show'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2480: in function `LFGListSearchPanel_SignUp'
[string "return function() "]:39: in function <[string "return function() "]:34>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}

**Comment by fang2hou** [comment]
It should be fixed in latest version.
