### ISSUE TITLE
[Feature Request] Add tooltip group info only for raid

### ISSUE THREAD

**Issue by Mistrick** [wind-addons/ElvUI_WindTools#391]
Blizz added own group info for M+ and now shows duplicate info. But the option is useful for the raid section.
Solutions:
1. Add an option - skip the tooltip in the M+ section
2. Replace Blizz tooltip but Blizz has a leader icon that can be added to your tooltip

**Comment by fang2hou** [comment]
added in 91a66879cfd7ed6d79c4eb0913edab028619f80a
