### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by NovaStarr724** [wind-addons/ElvUI_WindTools#393]
Message: Interface/AddOns/ElvUI_WindTools/Core/Core.lua:107: script ran too long
Time: Wed Jun 19 10:33:30 2024
Count: 1
Stack: Interface/AddOns/ElvUI_WindTools/Core/Core.lua:107: script ran too long
[string "=[C]"]: in function `(for generator)'
[string "@Interface/AddOns/ElvUI_WindTools/Core/Core.lua"]:107: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI_WindTools/Initialize.lua"]:68: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
[string "@Interface/AddOns/ElvUI/Core/init.lua"]:307: in function <Interface/AddOns/ElvUI/Core/init.lua:306>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ElvUI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...UI_Libraries/Core/Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: (*temporary) = <function> defined =[C]:-1

This is the Lua error message I get in the game.  Seeing that I'm not versed in Lua very much I thought it best to copy and paste the error message.  The problem is that the windtool doesn't show up at all let alone let me also load Toxi UI with it.  I have the addon selected in the addon window but when I got to start the install phase the addon was not there to select.  I hope this will assist you in working this out.  I'm not a programmer so I have very little knowledge on this especially since I never studied LUA.

Sincerely,
Barnabas (AKA NovaStarr)

**Comment by fang2hou** [comment]
It seems no problem now, if you still have same issue reopen this
