### ISSUE TITLE
[enhancement]Show player level inline with name in Chat

### ISSUE THREAD

**Issue by vderaa** [wind-addons/ElvUI_WindTools#396]
Hi,

Loving the Windtools addon, but was hoping you'd consider adding the following.

Display player level in chat pane.  For example [Player:Level] Said something in chat.

Many Thanks.

**Comment by fang2hou** [comment]
It requires more investagtion because it may scan the player information before the message shown.
in other word, it may cause the message delay, more traffic usage, and lower fps.
but as an option, it can be added in someday.
