### ISSUE TITLE
[Bug] WorldMap -> Reveal -> Use Colored Fog, is completely broken!

### ISSUE THREAD

**Issue by fubaWoW** [wind-addons/ElvUI_WindTools#408]
**Describe the bug**
see Screnshot

**To Reproduce**
1. Enable Feature

**Expected behavior**
should be clear ^^

**Screenshots**
![image](https://github.com/user-attachments/assets/cefddad1-b910-4851-a9fd-a571fbeef917)

**Information (you can find these in [WindTools-Information]):**
![image](https://github.com/user-attachments/assets/271e1205-b136-4bc3-9664-c5145cd20964)

**Comment by fang2hou** [comment]
Fixed in latest version.
