### ISSUE TITLE
[Bug]error

### ISSUE THREAD

**Issue by slyzor27** [wind-addons/ElvUI_WindTools#410]
8x [ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI_WindTools' tried to call the protected function 'UseQuestLogSpecialItem()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `UseQuestLogSpecialItem'
[string "@Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua"]:94: in function <...ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:87>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by Merathilis** [comment]
We already have a Bug Report on this, so don't need to open an other for it:

https://github.com/wind-addons/ElvUI_WindTools/issues/409
