### ISSUE TITLE
[Bug] Minimap Buttons

### ISSUE THREAD

**Issue by Darkwing151** [wind-addons/ElvUI_WindTools#415]
Hey,

i face an issue where the settings for "Maps > Minimap Buttons" are not saved correctly.
Only the position is saved consistently.

To reproduce this, i create a new character, select shared profile on start ant the settings are reset to the following:
![grafik](https://github.com/user-attachments/assets/c8a89309-b192-47da-8685-ed62bf7ccc12)

Expected (or saved config) should be:
Orientation: Vertical
Buttons Per Row: 1
Button Size: 15
Button Spacing: 1
Expansion Landing Page : checked

expected:
![grafik](https://github.com/user-attachments/assets/68d26032-5eb9-4aa4-af05-438708b264e4)

on new char:
![grafik](https://github.com/user-attachments/assets/411de28d-f70b-4643-9ca1-96042fc279f6)

Sometimes the orientation is vertical with "horizontal" stated in the settings.
This may lead to the conclusion, that the config is not correctly saved for me.

- Addon Version: 3.66
- ElvUI Version: 13.74
- WoW Build: 11.0.2 (56162)

**Comment by fang2hou** [comment]
Because of Minimap Buttons module saves the config in ElvUI Private Database, which different with ElvUI Profile Database.
You can use same or just import/export the private setting in ElvUI Options - Profile - Private

**Comment by AghaHuseyn** [comment]
Thank you for asking this question @Darkwing151 and thank you for pointing out the steps to eliminate this problem @fang2hou. 
I was just curious if there is a possibility in the future to make this configuration migrate with the other part of the profile in non-private. 
As I have a lot of alts and when I change something, applying it to every character is a bit too much time-consuming.
