### ISSUE TITLE
[Bug] DeathStrikeEstimator Error

### ISSUE THREAD

**Issue by Saw249** [wind-addons/ElvUI_WindTools#416]
## Describe the bug

DeathStrikeEstimator throws LUA errors

## To Reproduce

Play DK

## Information

- Addon Version: 3.66
- ElvUI Version: 13.74
- WoW Build: 11.0.2.56162

## Additional context

Message: WindTools [ERROR]
.../Modules/Combat/ClassHelper/DeathStrikeEstimator.lua:34: attempt to index local 'auraData' (a nil value)
Time: Sun Aug 18 19:13:29 2024
Count: 788
Stack: WindTools [ERROR]
.../Modules/Combat/ClassHelper/DeathStrikeEstimator.lua:34: attempt to index local 'auraData' (a nil value)
[string "@Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <Interface/AddOns/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: this = AceEvent30Frame {
}
event = "UNIT_AURA"
events = <table> {
 recurse = 1
 events = <table> {
 }
}

**Comment by AngelosNaoumis** [comment]
change line 34 till 41 to that
        if (auraData) then
            local name, stacks, spellId = auraData.name, auraData.applications, auraData.spellId
            if not name then
                return
            end
    
            if spell == spellId then
                return name, stacks
            end
        end
