### ISSUE TITLE
[Bug]更新了3.66之后 帧数上下波动很严重

### ISSUE THREAD

**Issue by Herryhan15** [wind-addons/ElvUI_WindTools#418]
## 描述问题

排查之后，载入wind工具箱之后，帧数一下300 一下200，关掉之后就稳定在360，朋友的电脑帧数一下90，一下20
也没有lua报错，就不知道怎么排查问题。

拍了视频发nga，不知道github这怎么发视频。
https://nga.178.com/read.php?tid=41334481

**Comment by fang2hou** [comment]
在 3.66 发布10分钟内，已经紧急发布了 3.66-fix-1 和 3.66-fix-2，请自行用 Curse / Wago / WoWInterface / GitHub 下载最新版本.
而且现在最新版本更新到了 3.67.
