### ISSUE TITLE
[Bug] Issue with Tooltip Spec Icon

### ISSUE THREAD

**Issue by Nethilas** [wind-addons/ElvUI_WindTools#419]
## Describe the bug

When disabling "Race Icon" under Tooltips -> General it also hides the new Spec Icon regardless if "Spec Icon" is checked or not.

## To Reproduce

1. Go to 'Tooltips -> General'
2. Uncheck Icon 'Race Icon'
4. Spec Icon is now gone on the tooltip

## Screenshots

![image](https://github.com/user-attachments/assets/499cfec8-b7d8-4526-80e2-aa1652f7751f)

## Information

- Addon Version: 3.67
- ElvUI Version 13.74
- WoW Build 11.0.2.56162

**Comment by fang2hou** [comment]
Thanks for your very detailed debug info, it has been fixed in latest fix version.
