### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Squimbert** [wind-addons/ElvUI_WindTools#422]
Would it be possible to add an option to scale the spec icon in the tooltip?
![image](https://github.com/user-attachments/assets/70ca9162-9fc2-4eb6-a318-3f06db32fe19)
It feels too big and I would like it to be more in line with my tooltip font.

**Comment by fang2hou** [comment]
Now the size is calculated from elvui tooltip text font size.
The height should be same as your font size.

**Comment by fang2hou** [comment]
Anyway, I added the options for all icon size in 3.68
