### ISSUE TITLE
[Bug] Move Frames breaks Hero Talent Tree

### ISSUE THREAD

**Issue by Dajova** [wind-addons/ElvUI_WindTools#430]
## Describe the bug

The "Move Frames" option breaks talent tree after TWW.
Blizzard Error logs caused by plugin: https://gist.github.com/Dajova/293f51ce19dd400db7a6d0f5e370e62c

## To Reproduce

1. Enable "Move Frames".
2. Switch or add talent point in the hero talent tree.
3. Apply said talent and/or tree.
4. Tree breaks and spews out errors.

## Expected behavior

Switching/adding point would cause no error nor break window.

## Screenshots

![image](https://i.imgur.com/73ctsSf.png)

## Additional context

No error on the actual plugin itself, but it breaks Blizzards addons. Only way i noticed it was Windtools was because of this small line:
` windFrameName = "PlayerSpellsFrame.TalentsFrame.ButtonsParent"`

https://eu.forums.blizzard.com/en/wow/t/did-the-game-just-wipe-an-entire-loadout-for-nothing/531269

**Comment by fang2hou** [comment]
Do you use latest version (3.72-fix-2)?

**Comment by Dajova** [comment]
Yes, everything is up-to-date. And this issue persists after disabling all addons, as explained. Only by resetting the frame positions does it fix itself, until you reproduce the steps again.
I have tried with both ProjectAzilroka and MoveAny and neither of them produce the same errors. In fact, i noticed it messed up with Kaliel's Tracker as well until i reseted the positions again. Same sort of errors, but with their frames.

**Comment by fang2hou** [comment]
I cannot reproduce this in my game.
Can you try `/wtdebug on` ?

**Comment by fang2hou** [comment]
And windtools do not have any code to move frames other than blizzard's.

**Comment by Dajova** [comment]
> And windtools do not have any code to move frames other than blizzard's.

Yes, this is what was it triggering. I posted the error on their page as well: https://legacy.curseforge.com/wow/addons/kaliels-tracker?page=5#c2081
It was trying to set a point to the world map (or something) and kaliels was also trying to move it (as i understand it), causing the bug, and resetting positions fixed it.

As for reproducing the bug, it seems to have stopped now that i've hit max level. It was present when i was still lvling up. I'll get another character to 71 and then report back to see if it happens again.

**Comment by Dajova** [comment]
Alright, i was able to replicate the issue. It has to be a lvl 71-79 character for this bug to trigger.

`2x ...pells/ClassTalents/Blizzard_HeroTalentsContainer.lua:510: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: Button:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:510: in function `UpdateHeroTalentButtonPosition'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:472: in function `UpdateContainerVisibility'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:562: in function <...pells/ClassTalents/Blizzard_HeroTalentsContainer.lua:558>
[string "=(tail call)"]: ?
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua"]:52: in function <...ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua:44>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:901: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:891>
[string "=[C]"]: ?
[string "=[C]"]: in function `HideUIPanel'
[string "@Blizzard_SharedXML/Mainline/SharedUIPanelTemplates.lua"]:154: in function <...izzard_SharedXML/Mainline/SharedUIPanelTemplates.lua:145>`

Essentially, when you first try to add a point to the hero talent tree, just activate it, exit the hero tree back to the normal tree and it triggers, breaking the window.
![image](https://i.imgur.com/wtapzsP.png)
... and yes, this was with `/wtdebug on`.

**Comment by fang2hou** [comment]
@Dajova
The move bug is caused by Blizzard, and I checked other addon found the fix code.
The memory thing is not the 'leak', because blizzard's new C_XXX API always returns full data after calling the API, recently the battle.net disconnection may cause huge amount event triggers, such that the friend info API will be called about 200 times once the disconnection happened, I already add a small logic to avoid too many times updates in 1 second.

**Comment by fang2hou** [comment]
The fix will be included in next fix version.
Thanks for your reporting!

**Comment by Dajova** [comment]
Still getting errors and still breaks the window.

``1x ...ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua:432: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: Button:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua"]:432: in function `PlaceHeroTalentButton'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua"]:141: in function `PlaceHeroTalentButton'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:480: in function `UpdateHeroTalentButtonPosition'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:657: in function `UpdateTalentButtonPosition'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:822: in function `InstantiateTalentButton'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:1267: in function `LoadTalentTreeInternal'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:800: in function `LoadTalentTreeInternal'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:1254: in function `LoadTalentTree'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:1142: in function `SetTalentTreeID'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:868: in function `SetTalentTreeID'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:864: in function `SetConfigID'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:356: in function `OnTraitConfigUpdated'
[string "@Blizzard_SharedTalentUI/Blizzard_SharedTalentFrame.lua"]:338: in function `OnEvent'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:338: in function <...erSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua:267>``

``1x ...pells/ClassTalents/Blizzard_HeroTalentsContainer.lua:510: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: Button:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:510: in function `UpdateHeroTalentButtonPosition'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:472: in function `UpdateContainerVisibility'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsContainer.lua"]:562: in function <...pells/ClassTalents/Blizzard_HeroTalentsContainer.lua:558>
[string "=(tail call)"]: ?
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua"]:52: in function <...ClassTalents/Blizzard_HeroTalentsSelectionDialog.lua:44>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_UIParentPanelManager/Mainline/UIParentPanelManager.lua"]:901: in function <...ParentPanelManager/Mainline/UIParentPanelManager.lua:891>
[string "=[C]"]: ?
[string "=[C]"]: in function `HideUIPanel'
[string "@Blizzard_SharedXML/Mainline/SharedUIPanelTemplates.lua"]:154: in function <...izzard_SharedXML/Mainline/SharedUIPanelTemplates.lua:145>``

Still triggering, even tho it's slightly changed. Now it triggers if you exit the window before spending all points.

**Comment by fang2hou** [comment]
As I mentioned above, the fix will be included in the next fix version, which is not released yet

**Comment by Dajova** [comment]
> As I mentioned above, the fix will be included in the next fix version, which is not released yet

Oh, ok. There was a new version when i updated today, so i figured that was the one you mentioned (as it had no specific "fix" attached to it). Nwm then.
