### ISSUE TITLE
[Bug] WarpBattleNet Function提示

### ISSUE THREAD

**Issue by Alpacos** [wind-addons/ElvUI_WindTools#436]
## 描述问题
更新插件到3.75以后，WA也有回滚功能的提示

然后就一直出现 Warp Battlenet Function提示，有几种不同的代码

### 错误复现步骤

登录以后能看到，好友上线以后能看到

## 预期功能

不应该出现warp的提示

## 截图

在reinstall windtool以后解决了，未留有截图

## 插件信息

(请填写基本信息，你可以在 [信息] 中找到)

- 插件版本：[例：3.75]
- ElvUI 版本 [例：13.76]
- 游戏版本 [例：11.0.2 (build 56461)]

## 更多信息

如果你有更多信息，在这里填写。

**Comment by fang2hou** [comment]
已经修复了，只是昨天 Curse 崩了在等 Curse 恢复后才更新 fix-1 版本
