### ISSUE TITLE
[Bug] 额外物品条开启时，每次释放技能都会略微卡顿

### ISSUE THREAD

**Issue by HolicXXX** [wind-addons/ElvUI_WindTools#442]
## Describe the bug

额外物品条开启时，释放技能时都会稍有顿挫感，关闭之后就很丝滑

## To Reproduce

1. 开启额外物品条
2. 释放任意技能

## Information

- Addon Version: 3.77
- ElvUI Version: 13.77

**Comment by Maoh83** [comment]
Thx to you,
I searched all day which module was causing the problem, it had become unbearable, with each jump/flight the game had a drop in FPS to 3, then returned a few hundredths later.

I had to disable the extra item bars, and my problems flew away with my utilities...!

**Comment by HolicXXX** [comment]
Same here, it took me 3 hours to locate this annoy problem, hope it will get fixed soon.

**Comment by fang2hou** [comment]
This have been fixed in latest fix version `3.77-fix-1`.
