### ISSUE TITLE
[Bug]Local (error) - 403

### ISSUE THREAD

**Issue by GustDK** [wind-addons/ElvUI_WindTools#444]
62x ...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:109: attempt to compare number with nil
[string "@ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua"]:109: in function <...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:73>
[string "=(tail call)"]: ?
[string "@ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:584: in function `_GameTooltip_OnTooltipSetUnit'
[string "@ElvUI_WindTools/Modules/Tooltips/Core.lua"]:190: in function <...aceElvUI_WindTools/Modules/Tooltips/Core.lua:189>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function `ProcessInfo'
[string "@Blizzard_GameTooltip/Mainline/GameTooltip.lua"]:941: in function `SetWorldCursor'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:1367: in function <...rfaceBlizzard_UIParent/Mainline/UIParent.lua:1290>

Locals:
self = <table> {
 modules = <table> {
 }
 baseName = "ElvUI_WindTools"
 clearInspect = <table> {
 }
 eventCallback = <table> {
 }
 modifierInspect = <table> {
 }
 defaultModuleState = true
 load = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 initialized = true
 profiledb = <table> {
 }
 name = "ElvUI_WindTools_Tooltips"
 orderedModules = <table> {
 }
 hooks = <table> {
 }
 normalInspect = <table> {
 }
 updateProfile = <table> {
 }
 moduleName = "Tooltips"
}
mod = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 Initialized = true
 baseName = "ElvUI"
 name = "ElvUI_Tooltip"
 orderedModules = <table> {
 }
 moduleName = "Tooltip"
}
tt = GameTooltip {
 ItemTooltip = Frame {
 }
 shadow = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 windInspectLoaded = false
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 __windShadow = 1
 numMoneyFrames = 2
 PixelSnapDisabled = true
 supportsDataRefresh = true
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 waitingForData = false
 factionFrame = Texture {
 }
 updateTooltipTimer = 0.178000
 shoppingTooltips = <table> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 supportsItemComparison = true
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
unit = "nameplate1"
db = <table> {
 enable = true
 iconWidth = 18
 icon = true
 iconHeight = 16
}
data = <table> {
 updated = 1726614523
 highestScoreDungeonIndex = 1
 runs = <table> {
 }
 currentSeasonScoreColor = <table> {
 }
 highestScoreDungeonID = 501
 currentSeasonScore = 351
}
mapData = <table> {
 abbr = "SV"
 name = "The Stonevault"
 tex = 5912515
 timeLimit = 1980
 activityID = 328
 idString = "501"
}
run = <table> {
 mapScoreColor = <table> {
 }
 bestRunLevelColor = "ffffff"
 challengeModeID = 501
 bestRunDurationMS = 1276820
 finishedSuccess = true
 mapScore = 178
 bestRunLevel = 2
}
bestRunLevelText = "|cff1eff002|r"
(*temporary) = nil
(*temporary) = 2
(*temporary) = "ff1eff00"
(*temporary) = "|cff1eff002|r"
(*temporary) = "|c%s%s|r"
(*temporary) = "ff1eff00"
(*temporary) = "2"
(*temporary) = "|cff1eff002|r"
(*temporary) = nil
(*temporary) = nil
(*temporary) = 255
(*temporary) = "attempt to compare number with nil"
ET = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 Initialized = true
 baseName = "ElvUI"
 name = "ElvUI_Tooltip"
 orderedModules = <table> {
 }
 moduleName = "Tooltip"
}
L = <table> {
 Confirm Summon = "Confirm Summon"
 Animation Duration = "Animation Duration"
 Online Friends = "Online Friends"
 Alert will be disabled after the set value (hours). = "Alert will be disabled after the set value (hours)."
 Automate your game life. = "Automate your game life."
 Animation Size = "Animation Size"
 WindTools Modules = "|cff5385edW|r|cff5094eai|r|cff4da4e7n|r|cff4ab4e4d|r|cff47c0e1T|r|cff44cbdfo|r|cff41d7ddo|r|cff41d7ddl|r|cff41d7dds|r Modules"
 %player% interrupted %target%'s %target_spell%! = "%player% interrupted %target%'s %target_spell%!"
 Raid = "Raid"
 Add a contact frame beside the mail frame. = "Add a contact frame beside the mail frame."
 Next Affixes = "Next Affixes"
 Auto-detect = "Auto-detect"
 Food = "Food"
 ElvUI Tooltip Tweaks = "ElvUI Tooltip Tweaks"
 LEFT = "LEFT"
 BigfootWorldChannel = "BigfootWorldChannel"
 The first button anchors itself to this point on the bar. = "The first button anchors itself to this point on the bar."
 This will change the layout of your unitframes and actionbars. = "This will change the layout of your unitframes and actionbars."
 Covenant Preview = "Covenant Preview"
 MerathilisUI = "|cffffffffMerathili

**Comment by LennoxP90** [comment]
+1

**Comment by LennoxP90** [comment]
the error occurs when I hover over a person with M+ io score only

**Comment by legrimm** [comment]
Getting same issue with a M+ io score... didn't realize that was was triggering. 

Message: ...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:109: attempt to compare number with nil
Time: Tue Sep 17 18:23:59 2024
Count: 4
Stack: ...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:109: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua"]:109: in function <...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:73>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:584: in function `_GameTooltip_OnTooltipSetUnit'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Tooltips/Core.lua"]:190: in function <...ace/AddOns/ElvUI_WindTools/Modules/Tooltips/Core.lua:189>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function `ProcessInfo'
[string "@Interface/AddOns/Blizzard_GameTooltip/Mainline/GameTooltip.lua"]:941: in function `SetWorldCursor'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:1367: in function <...rface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua:1290>
[string "=[C]"]: ?

Locals:

**Comment by fang2hou** [comment]
already fixed in git, later you can find 3.78 in curse.
