### ISSUE TITLE
[Bug] -Lua Error after todays Update... 

### ISSUE THREAD

**Issue by legrimm** [wind-addons/ElvUI_WindTools#445]
Message: ...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:109: attempt to compare number with nil
Time: Tue Sep 17 18:23:59 2024
Count: 4
Stack: ...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:109: attempt to compare number with nil
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua"]:109: in function <...dOns/ElvUI_WindTools/Modules/Tooltips/MythicPlus.lua:73>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:584: in function `_GameTooltip_OnTooltipSetUnit'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Tooltips/Core.lua"]:190: in function <...ace/AddOns/ElvUI_WindTools/Modules/Tooltips/Core.lua:189>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function `ProcessInfo'
[string "@Interface/AddOns/Blizzard_GameTooltip/Mainline/GameTooltip.lua"]:941: in function `SetWorldCursor'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:1367: in function <...rface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua:1290>
[string "=[C]"]: ?

Locals:

**Comment by fang2hou** [comment]
already fixed in git, later you can find 3.78 in curse.
