### ISSUE TITLE
[Bug] friendslist informations

### ISSUE THREAD

**Issue by Zwegert** [wind-addons/ElvUI_WindTools#447]
## Describe the bug
The Friendslist does not show further informations as it is set in the WindTool options. 

## To Reproduce
1. Go to 'friends'
 via Mouseover

## Screenshots

![WTFehler](https://github.com/user-attachments/assets/ebafc990-8f0b-4b3a-8488-fc54e201cd7e)

## Information
you can find these in [WindTools-Information]
- Addon Version: 3.80
- ElvUI Version: 13,78
- WoW Build: 11.0.2.56647

**Comment by fang2hou** [comment]
your screenshot is ElvUI friend datatext. WindTools friend list is a module to modify your blizzard friend list frame

**Comment by Zwegert** [comment]
Oh yes i see, sry for that, but  i can remember, that the ElvUI Friendlist was full of further infos. Did it never come with ElvUI Windtool? (i can't remember because of a break of 2 years)

**Comment by fang2hou** [comment]
Never. If it is related, the description will include it.
