### ISSUE TITLE
[功能建议] 预组增强里，[职责可用]和[有T]能否可以同时勾选

### ISSUE THREAD

**Issue by Se7enMuting** [wind-addons/ElvUI_WindTools#450]
提个小建议，预组增强里面，[职责可用]和[有T]能否可以同时勾选，比如我是奶妈，我就是想找已经有T的队伍。
另外，上面的词缀说明里一直是第一周的扬生。

**Comment by fang2hou** [comment]
词缀说明已经更新了，预组那个功能你可以在设定里改的。
