### ISSUE TITLE
[Bug] RareScanner 美化功能建议

### ISSUE THREAD

**Issue by Kai2guo** [wind-addons/ElvUI_WindTools#451]
左上角是超级追踪，很好用

中间红色是RareScanner的搜索框，回去以前地图找精英的时候很好用，但他原生界面很丑，

如果咱们的美化能将这个搜索框移动到绿色和超级追踪的坐标输入框齐平，将是绝杀，背景再写上文字RareScanner搜索器
![微信图片_20241016053527](https://github.com/user-attachments/assets/c30c1997-66c9-438f-ab99-818261e7e9e2)

应该是可以实现的，因为我也装了ElvUI Eltruism，他是这样的，很丑
![微信截图_20241016054634](https://github.com/user-attachments/assets/66b09414-3f86-4f44-b3c3-dab0f864f7c9)

**Comment by Kai2guo** [comment]
![Uploading 微信截图_20241016054634.png…]()

**Comment by fang2hou** [comment]
嗯，可以稍微改一下

**Comment by fang2hou** [comment]
added in 06d32d52179ae57251ab85bdeca69570ba318a6c

**Comment by fang2hou** [comment]
![image](https://github.com/user-attachments/assets/3c94c53f-f976-4395-b0d3-4c9ea9d4a542)
