### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by hknylmz-wow** [wind-addons/ElvUI_WindTools#454]
## Describe the bug
When Pet Battle is won, the Chat panel shows a command but no text.
Instead of text, it says “PET_BATTLE_INFO”.

![image](https://github.com/user-attachments/assets/6713fcf6-bb93-4db6-bf0f-0a1948f93fc4)

## Information

you can find these in [WindTools-Information]

- Addon Version: [e.g. 3.83]
- ElvUI Version [e.g. 13.80]
- WoW Build [e.g. 11.0.5 (57388)]

**Comment by fang2hou** [comment]
This bug should not come from WindTools
