### ISSUE TITLE
Addon skin compatibility for WarpDeplete

### ISSUE THREAD

**Issue by happenslol** [wind-addons/ElvUI_WindTools#456]
Hey, I'm the author of WarpDeplete, which you addon provides a skin for.

I'm in the process of a big refactor of the addon, which changes how a lot of the internal rendering logic works, and changes some function names. It seems like you're hooking some of my functions, so I wanted to give a heads up here before I release anything so that people don't run into lua errors and have to disable your addon or the skins.

The current `main` branch of my WarpDeplete repository already includes all of the changes, and a beta version has already been released. How do you want to handle this? I'm open to answering any questions about the changes here.

**Comment by fang2hou** [comment]
Thanks for your message before releasing.
I will update the skin later today.

**Comment by fang2hou** [comment]
added in 2a92b6aadf2ff930f9b5774d4312c0213fa48ed1
