### ISSUE TITLE
[Bug] I'm constantly getting this error

### ISSUE THREAD

**Issue by Hsu75** [wind-addons/ElvUI_WindTools#458]
152207x ElvUI_WindTools/Modules/Tooltips/UnitInfo.lua:49: attempt to call field 'GetRaceAtlasString' (a nil value)
[string "@ElvUI_WindTools/Modules/Tooltips/UnitInfo.lua"]:49: in function <ElvUI_WindTools/Modules/Tooltips/UnitInfo.lua:22>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetUnitText'
[string "@ElvUI/Core/Modules/Tooltip/Tooltip.lua"]:567: in function `_GameTooltip_OnTooltipSetUnit'
[string "@ElvUI_WindTools/Modules/Tooltips/Core.lua"]:191: in function <...aceElvUI_WindTools/Modules/Tooltips/Core.lua:190>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
...
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "@Blizzard_UnitFrame/UnitFrame.lua"]:390: in function `UnitFrame_UpdateTooltip'
[string "@Blizzard_UnitFrame/UnitFrame.lua"]:380: in function <Blizzard_UnitFrame/UnitFrame.lua:379>
[string "@ElvUI/Core/Modules/UnitFrames/UnitFrames.lua"]:284: in function <ElvUI/Core/Modules/UnitFrames/UnitFrames.lua:283>
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:266: in function <Blizzard_FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Blizzard_FrameXML/SecureHandlers.lua"]:322: in function <Blizzard_FrameXML/SecureHandlers.lua:306>
[string "=(tail call)"]: ?

Locals:
self = <table> {
 modules = <table> {
 }
 baseName = "ElvUI_WindTools"
 clearInspect = <table> {
 }
 eventCallback = <table> {
 }
 modifierInspect = <table> {
 }
 defaultModuleState = true
 load = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 comparisonLoaded = true
 initialized = true
 profiledb = <table> {
 }
 name = "ElvUI_WindTools_Tooltips"
 orderedModules = <table> {
 }
 hooks = <table> {
 }
 normalInspect = <table> {
 }
 updateProfile = <table> {
 }
 moduleName = "Tooltips"
}
_ = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 Initialized = true
 baseName = "ElvUI"
 name = "ElvUI_Tooltip"
 orderedModules = <table> {
 }
 moduleName = "Tooltip"
}
tt = GameTooltip {
 ItemTooltip = Frame {
 }
 shadow = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 hasMoney = 1
 textRight2Font = "GameTooltipText"
 windInspectLoaded = false
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 __windShadow = 1
 numMoneyFrames = 2
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 supportsDataRefresh = true
 shouldRefreshData = false
 waitingForData = false
 __tooltipUpdated = false
 updateTooltipTimer = 0.027000
 shoppingTooltips = <table> {
 }
 TextRight1 = GameTooltipTextRight1 {
 }
 supportsItemComparison = true
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
unit = "player"
isPlayerUnit = true
etdb = <table> {
 raceIcon = <table> {
 }
 betterMythicPlusInfo = <table> {
 }
 forceItemLevel = false
 specIcon = <table> {
 }
}
guildName = "피프"
levelLine = GameTooltipTextLeft3 {
}
specLine = GameTooltipTextLeft4 {
}
level = 80
realLevel = 80
diffColor = <table> {
 b = 0
 font = "QuestDifficulty_Difficult"
 g = 0.820000
 r = 1
}
race = "인간"
englishRace = "Human"
gender = 3
_ = "Alliance"
localizedFaction = "얼라이언스"
hexColor = "|cffffd100"
unitGender = false
(*temporary) = nil
(*temporary) = "Human"
(*temporary) = 3
(*temporary) = 16
(*temporary) = 16
(*temporary) = "attempt to call field 'GetRaceAtlasString' (a nil value)"
ET = <table> {
 modules = <table> {
 }
 defaultModuleState = true
 hooks = <table> {
 }
 db = <table> {
 }
 enabledState = true
 defaultModuleLibraries = <table> {
 }
 Initialized = true
 baseName = "ElvUI"
 name = "ElvUI_Tooltip"
 orderedModules = <table> {
 }
 moduleName = "Tooltip"
}
E = <table> {
 mylevel = 80
 Bags = <table> {
 }
 privateVars = <table> {
 }
 modules = <table> {
 }
 myspecRole = "HEALER"
 PriestColors = <table> {
 }
 db = <table> {
 }
 Layout = <table> {
 }
 Distributor = <table> {
 }
 MountText = <table> {
 }
 INCOMPATIBLE_ADDONS = <table> {
 }
 TimeIndicatorColors = <table> {
 }
 WorldMap = <table> {
 }
 TimeColors = <table> {
 }
 ShortValueDec = "%.0f"
 oUF = <table> {
 }
 Classic = false
 myrole = "HEALER"
 UFParent = ElvUFParent {
 }
 InfoColor2 = "|cff9b9b9b"
 myname = "페피는냥냥"
 ActionBars = <table> {
 }
 DebugTools = <table> {
 }
 twoPixelsPlease = false
 ConfigModeLayouts = <table> {
 }
 DataTexts = <table> {
 }
 ClassName = <table> {
 }
 CreatureTypes = <table> {
 }
 Auras = <table> {
 }
 private = <table> {
 }
 ReverseTimer = <table> {
 }
 TagFunctions = <table> {
 }
 myClassID = 5
 UnlocalizedClasses = <table> {
 }
 MinimapSize = 223
 callbacks = <table> {
 }
 hooks = <table> {
 }
 SpecName = <table> {
 }
 GemTypeInfo = <table> {
 }
 StyleFilterDefaults = <table> {
 }
 physicalWidth = 1920
 versionString = "13.78"
 LSM = <table> {
 }
 InfoColor = "|cff1784d1"
 AFK = <table> {
 }
 CreatedMovers = <table> {
 }
 myLocalizedFaction = "얼라이언스"
 myrace = "Human"
 StaticPopup_DisplayedFrames = <table> {
 }
 VehicleLocks = <table> {
 }
 myLocalizedRace = "인간"
 myclass = "PRIEST"
 wowdate = "Oct 22 2024"
 Masque = <table> {
 }
 PopupDialog

**Comment by fang2hou** [comment]
Please provide all needed information with this [template](https://github.com/wind-addons/ElvUI_WindTools/issues/new?assignees=&labels=bug&projects=&template=bug_enUS.md&title=%5BBug%5D)
