### ISSUE TITLE
[Bug] Enabling OmniCD skin throws errors

### ISSUE THREAD

**Issue by sKullsen** [wind-addons/ElvUI_WindTools#462]
## Describe the bug

Enabling Omn iCD skin throws errors:

WindTools [ERROR]
...dOns/ElvUI_WindTools/Modules/Skins/Addons/OmniCD.lua:27: hooksecurefunc(): AcquireIcon is not a function
Count: 1

Call Stack:
[string "@Interface/AddOns/ElvUI_WindTools/Core/Functions/Developer.lua"]:67: in function <.../AddOns/ElvUI_WindTools/Core/Functions/Developer.lua:65>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Skins/Addons/OmniCD.lua"]:27: in function `OmniCD_Party_Icon'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Skins/Addons/OmniCD.lua"]:81: in function <...dOns/ElvUI_WindTools/Modules/Skins/Addons/OmniCD.lua:75>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Skins/Core.lua"]:336: in function `CallLoadedAddon'
[string "@Interface/AddOns/ElvUI_WindTools/Modules/Skins/Core.lua"]:514: in function <...erface/AddOns/ElvUI_WindTools/Modules/Skins/Core.lua:499>
[string "=[C]"]: ?
[string "@Interface/AddOns/ElvUI_WindTools/Core/Core.lua"]:115: in function `InitializeModules'
[string "@Interface/AddOns/ElvUI_WindTools/Initialize.lua"]:110: in function `?'
[string "@Interface/AddOns/ElvUI_Libraries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua"]:309: in function <...aries/Core/LibElvUIPlugin-1.0/LibElvUIPlugin-1.0.lua:305>
[string "=[C]"]: in function `Initialize'
...
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua"]:630: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:96: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:89: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:84: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:76: in function <...pansionLandingPage/Blizzard_WarWithinLandingPage.lua:72>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_WarWithinLandingPage.lua"]:48: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:82: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

## To Reproduce

Enable Skins -> Addons ->
OmniCD, OmniCD Icon, OmniCD Status Bar

## Expected behavior

Ideally no error :)

## Information

you can find these in [WindTools-Information]

- Addon Version: 3.86
- ElvUI Version 1380
- WoW Build 11.0.5 (57534)
-

**Comment by fang2hou** [comment]
What's your OmniCD version, is that latest `2.8.10`?
